"""Add persistent audit and approval evidence

Revision ID: 490034bcaf74
Revises: efc8645799f9
Create Date: 2026-09-13 16:34:47.536358

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '490034bcaf74'
down_revision: str | Sequence[str] | None = 'efc8645799f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.String(length=255), nullable=False),
    sa.Column('action_id', sa.String(length=255), nullable=False),
    sa.Column('approver_identity', sa.String(length=255), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_evidence_action_id'), 'approval_evidence', ['action_id'], unique=False)
    op.create_index(op.f('ix_approval_evidence_approval_id'), 'approval_evidence', ['approval_id'], unique=True)
    op.create_table('runtime_audit_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('agent_version_id', sa.String(length=255), nullable=False),
    sa.Column('passport_id', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('action_name', sa.String(length=255), nullable=False),
    sa.Column('requested_permissions', sa.JSON(), nullable=False),
    sa.Column('passport_status', sa.String(length=50), nullable=False),
    sa.Column('certified_configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('current_configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.String(length=255), nullable=True),
    sa.Column('approver_identity', sa.String(length=255), nullable=True),
    sa.Column('human_approved', sa.Boolean(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('principal_identity', sa.String(length=255), nullable=True),
    sa.Column('principal_roles', sa.JSON(), nullable=False),
    sa.Column('enforcement_reasons', sa.JSON(), nullable=False),
    sa.Column('execution_outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_audit_entries_action_id'), 'runtime_audit_entries', ['action_id'], unique=False)
    op.create_index(op.f('ix_runtime_audit_entries_approval_id'), 'runtime_audit_entries', ['approval_id'], unique=False)
    op.create_index(op.f('ix_runtime_audit_entries_event_id'), 'runtime_audit_entries', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runtime_audit_entries_event_id'), table_name='runtime_audit_entries')
    op.drop_index(op.f('ix_runtime_audit_entries_approval_id'), table_name='runtime_audit_entries')
    op.drop_index(op.f('ix_runtime_audit_entries_action_id'), table_name='runtime_audit_entries')
    op.drop_table('runtime_audit_entries')
    op.drop_index(op.f('ix_approval_evidence_approval_id'), table_name='approval_evidence')
    op.drop_index(op.f('ix_approval_evidence_action_id'), table_name='approval_evidence')
    op.drop_table('approval_evidence')
    # ### end Alembic commands ###
