"""Create SafetyGate core schema

Revision ID: efc8645799f9
Revises: 
Create Date: 2026-09-13 16:12:18.946758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc8645799f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('action_id', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_records_action_id'), 'execution_records', ['action_id'], unique=False)
    op.create_index(op.f('ix_execution_records_idempotency_key'), 'execution_records', ['idempotency_key'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_identity', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_agent_org_name')
    )
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.create_table('agent_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('memory_config', sa.JSON(), nullable=False),
    sa.Column('jurisdictions', sa.JSON(), nullable=False),
    sa.Column('autonomy_level', sa.String(length=50), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('certification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version_number', name='uq_agent_version')
    )
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_versions_configuration_hash'), 'agent_versions', ['configuration_hash'], unique=False)
    op.create_index(op.f('ix_agent_versions_organization_id'), 'agent_versions', ['organization_id'], unique=False)
    op.create_table('safety_passports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_version_id', sa.Uuid(), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=100), nullable=False),
    sa.Column('risk_class', sa.String(length=50), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('conditional_tools', sa.JSON(), nullable=False),
    sa.Column('prohibited_tools', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('certification_reason', sa.Text(), nullable=False),
    sa.Column('signature_key_id', sa.String(length=500), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_passports_agent_version_id'), 'safety_passports', ['agent_version_id'], unique=False)
    op.create_index(op.f('ix_safety_passports_configuration_hash'), 'safety_passports', ['configuration_hash'], unique=False)
    op.create_index(op.f('ix_safety_passports_organization_id'), 'safety_passports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_safety_passports_status'), 'safety_passports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_passports_status'), table_name='safety_passports')
    op.drop_index(op.f('ix_safety_passports_organization_id'), table_name='safety_passports')
    op.drop_index(op.f('ix_safety_passports_configuration_hash'), table_name='safety_passports')
    op.drop_index(op.f('ix_safety_passports_agent_version_id'), table_name='safety_passports')
    op.drop_table('safety_passports')
    op.drop_index(op.f('ix_agent_versions_organization_id'), table_name='agent_versions')
    op.drop_index(op.f('ix_agent_versions_configuration_hash'), table_name='agent_versions')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_execution_records_idempotency_key'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_action_id'), table_name='execution_records')
    op.drop_table('execution_records')
    # ### end Alembic commands ###
